"""
Regenerate publication-quality figures for the final paper.

Every figure is designed to be self-explanatory: title states the finding
(not the method), values are annotated on bars, colors carry meaning
(green = positive predictor, red = negative, gray = null), and captions
in the plot titles guide interpretation.

Figures produced (numbering matches Paper_Draft.md appendix):
  02  AAA wRC+ vs MLB wRC+ scatter — the motivation
  03  Skill coefficients — THE HEADLINE
  05  Model comparison — head-to-head predictive accuracy
  08  Coefficient robustness across survivorship corrections
  09  Before/after specification correction — the methodological story (NEW)

Other diagnostic figures (01 heatmap, 04 residuals, 06 pred-vs-actual, 07
selection) are left untouched — they're generated by the analysis scripts
and are already fine for a supplementary appendix.
"""

from __future__ import annotations
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data" / "processed" / "matched_players.csv"
COEFS = ROOT / "data" / "processed" / "regression_coefficients.csv"
STEP3 = ROOT / "data" / "processed" / "step3_model_comparison.csv"
SURV = ROOT / "data" / "processed" / "survivorship_corrected_coefs.csv"
SENS = ROOT / "data" / "processed" / "sensitivity_coefficients.csv"
FIGS = ROOT / "figures"
FIGS.mkdir(exist_ok=True)

# ---- Consistent styling ----
plt.rcParams.update({
    "font.family": "DejaVu Sans",
    "font.size": 12,
    "axes.titlesize": 15,
    "axes.labelsize": 13,
    "xtick.labelsize": 11,
    "ytick.labelsize": 11,
    "legend.fontsize": 11,
    "figure.dpi": 100,
    "savefig.dpi": 200,
    "savefig.bbox": "tight",
    "axes.spines.top": False,
    "axes.spines.right": False,
    "axes.grid": True,
    "grid.linestyle": ":",
    "grid.alpha": 0.5,
})

COLOR_POS = "#2E9E4F"   # green — translates positively
COLOR_NEG = "#D64545"   # red   — translates negatively
COLOR_NULL = "#888888"  # gray  — statistically null
COLOR_BASE = "#5477A6"  # muted blue — baseline
COLOR_WIN = "#7A4FB0"   # purple — winning combined model


def add_title_and_subtitle(fig, title: str, subtitle: str,
                           title_y: float = 0.98, subtitle_y: float = 0.925) -> None:
    """Place a bold title and italic subtitle above the axes without overlap.

    Uses figure coordinates so the two lines are guaranteed separate. Callers
    should reserve top-margin space with fig.subplots_adjust(top=...) or an
    equivalent tight_layout(rect=...) after this call.
    """
    fig.text(0.5, title_y, title, ha="center", va="top",
             fontsize=17, fontweight="bold")
    fig.text(0.5, subtitle_y, subtitle, ha="center", va="top",
             fontsize=11.5, color="#333", style="italic")


# =============================================================================
# FIGURE 02 — AAA wRC+ vs MLB wRC+ scatter (motivation)
# =============================================================================
def figure_02(df: pd.DataFrame) -> None:
    sub = df[["aaa_wRC+", "mlb_wRC+", "mlb_PA"]].dropna()
    r = float(sub["aaa_wRC+"].corr(sub["mlb_wRC+"]))
    m, b = np.polyfit(sub["aaa_wRC+"], sub["mlb_wRC+"], 1)

    fig, ax = plt.subplots(figsize=(9.5, 6.5))
    # scatter — dot size proportional to sqrt of MLB PA (visualizes reliability)
    sizes = 8 + 40 * np.sqrt(sub["mlb_PA"] / sub["mlb_PA"].max())
    ax.scatter(sub["aaa_wRC+"], sub["mlb_wRC+"], s=sizes, alpha=0.35,
               color="#4477AA", edgecolor="none")

    xs = np.linspace(sub["aaa_wRC+"].min(), sub["aaa_wRC+"].max(), 100)
    ax.plot(xs, m*xs + b, color="black", lw=2.2, label=f"OLS fit  (r = {r:.2f})")
    ax.axhline(100, color="gray", ls="--", lw=1, alpha=0.6, zorder=0)
    ax.axvline(100, color="gray", ls="--", lw=1, alpha=0.6, zorder=0)
    ax.text(102, 155, "league average\nMLB wRC+ = 100", fontsize=10, color="gray")

    ax.set_xlabel("AAA wRC+  (career, PA-weighted, pre-debut)")
    ax.set_ylabel("MLB wRC+  (career, PA-weighted)")
    ax.legend(loc="lower right", framealpha=0.9)
    add_title_and_subtitle(
        fig,
        f"AAA wRC+ vs. MLB wRC+, matched cohort (N = {len(sub)})",
        f"AAA hitters 2015–2024 who reached MLB with 200+ PA. "
        f"OLS fit r = {r:.2f}; the wide vertical scatter around the line motivates "
        f"disaggregating wRC+ into its component skills.",
    )
    fig.subplots_adjust(top=0.83)
    fig.savefig(FIGS / "02_aaa_vs_mlb_wrcplus_scatter.png")
    plt.close(fig)
    print("wrote figures/02_aaa_vs_mlb_wrcplus_scatter.png")


# =============================================================================
# FIGURE 03 — THE HEADLINE FIGURE (skill coefficients)
# =============================================================================
def figure_03() -> None:
    coefs = pd.read_csv(COEFS)
    skill = coefs[coefs["model"] == "skill"].copy()

    labels_map = {
        "aaa_ISO_zseason":   "AAA ISO\n(power)",
        "aaa_K%_zseason":    "AAA K%\n(strikeouts)",
        "aaa_BB%_zseason":   "AAA BB%\n(walks)",
        "age_at_debut":      "Age at\nMLB debut",
        "aaa_BABIP_zseason": "AAA BABIP\n(luck)",
    }
    skill["label"] = skill["predictor"].map(labels_map)
    skill = skill.dropna(subset=["label"])
    skill = skill.reindex(skill["std_coef"].abs().sort_values().index)

    colors = []
    for _, row in skill.iterrows():
        if row["p_value"] > 0.05:
            colors.append(COLOR_NULL)
        elif row["std_coef"] > 0:
            colors.append(COLOR_POS)
        else:
            colors.append(COLOR_NEG)

    fig, ax = plt.subplots(figsize=(11, 6.5))
    bars = ax.barh(skill["label"], skill["std_coef"],
                   xerr=1.96 * skill["std_error"],
                   color=colors, edgecolor="black", linewidth=0.9, alpha=0.9,
                   error_kw={"lw": 1.5, "capsize": 4})
    ax.axvline(0, color="black", lw=1)

    # value labels
    for bar, val, p in zip(bars, skill["std_coef"], skill["p_value"]):
        if p < 0.001:
            stars = "***"
        elif p < 0.01:
            stars = "**"
        elif p < 0.05:
            stars = "*"
        else:
            stars = "n.s."
        offset = 0.35 if val > 0 else -0.35
        ha = "left" if val > 0 else "right"
        ax.text(val + offset, bar.get_y() + bar.get_height()/2,
                f"{val:+.2f} {stars}", va="center", ha=ha,
                fontweight="bold", fontsize=12.5)

    ax.set_xlabel("Standardized coefficient   ← lowers MLB wRC+   |   raises MLB wRC+ →",
                  labelpad=10)
    ax.text(0.5, -0.19,
            "***  p < 0.001    **  p < 0.01    *  p < 0.05    n.s.  not significant. "
            "Bars = predicted change in MLB wRC+ per 1 standard-deviation change in the AAA input.",
            transform=ax.transAxes, ha="center", va="top", fontsize=10, color="#555")

    lo = min(skill["std_coef"].min() * 1.15, -1)
    hi = max(skill["std_coef"].max() * 1.15, 1)
    span = max(abs(lo), abs(hi))
    ax.set_xlim(-span * 1.1, span * 1.1)
    add_title_and_subtitle(
        fig,
        "Standardized skill-model regression coefficients",
        "Bars show predicted change in MLB wRC+ per 1-SD change in each AAA predictor. "
        "Green = positive translator, red = negative, gray = null.",
    )
    fig.subplots_adjust(top=0.83, bottom=0.18)
    fig.savefig(FIGS / "03_skill_coefficients.png")
    plt.close(fig)
    print("wrote figures/03_skill_coefficients.png")


# =============================================================================
# FIGURE 05 — Model comparison (head-to-head)
# =============================================================================
def figure_05() -> None:
    # Values from the paired t-test output. Star convention matches Table 2:
    #   *** p < 0.001,  ** p < 0.01,  * p < 0.05,  n.s. otherwise.
    # p = 0.005 falls in the ** band (< 0.01 but not < 0.001).
    models = [
        ("Baseline\nraw AAA wRC+",           0.0614, 0.0035, None,   None,   None,   COLOR_BASE),
        ("Translation Score\n(5 skills)",     0.0599, 0.0063, -0.001, 0.52,  "TIE",   COLOR_NULL),
        ("Purified Score\n(no BABIP)",        0.0648, 0.0070, +0.003, 0.15,  "n.s.",  COLOR_NULL),
        ("Combined\nScore + wRC+",            0.0687, 0.0060, +0.007, 0.005, "**",    COLOR_WIN),
    ]

    fig, ax = plt.subplots(figsize=(11, 6.5))
    xs = np.arange(len(models))
    r2s = [m[1] for m in models]
    sds = [m[2] for m in models]
    colors = [m[6] for m in models]
    bars = ax.bar(xs, r2s, yerr=sds, color=colors, edgecolor="black",
                  linewidth=1, alpha=0.9, error_kw={"lw": 1.3, "capsize": 5})

    # value labels
    for i, (bar, m) in enumerate(zip(bars, models)):
        r2, _, delta, pval, verdict, _ = m[1:]
        ax.text(i, r2 + m[2] + 0.0025, f"{r2:.3f}", ha="center",
                fontweight="bold", fontsize=12)
        if delta is not None:
            sign = "+" if delta > 0 else ""
            is_win = verdict in ("**", "***")
            ax.text(i, -0.008, f"Δ = {sign}{delta:.3f}\np = {pval:.3f}   {verdict}",
                    ha="center", va="top", fontsize=10.5,
                    color=("darkgreen" if is_win else "#555"),
                    fontweight="bold" if is_win else "normal")

    ax.set_xticks(xs)
    ax.set_xticklabels([m[0] for m in models])
    ax.set_ylabel("Cross-validated R²  (higher = better)")
    ax.set_ylim(-0.025, 0.09)
    ax.axhline(models[0][1], color="gray", ls="--", lw=1, alpha=0.5, zorder=0)
    ax.text(3.35, models[0][1], " baseline", va="center", fontsize=9.5, color="gray")

    from matplotlib.patches import Patch
    legend_elems = [
        Patch(facecolor=COLOR_BASE, edgecolor="black", label="Baseline (raw wRC+)"),
        Patch(facecolor=COLOR_NULL, edgecolor="black", label="Not significantly better than baseline"),
        Patch(facecolor=COLOR_WIN,  edgecolor="black", label="Formally significant win"),
    ]
    # Place legend BELOW the plot area (horizontal) so it can never collide
    # with bar-value labels regardless of tallest bar.
    ax.legend(handles=legend_elems,
              loc="upper center", bbox_to_anchor=(0.5, -0.24),
              ncol=3, framealpha=0.9, frameon=True, fontsize=10.5)
    add_title_and_subtitle(
        fig,
        "Cross-validated projection accuracy across four models",
        "Head-to-head paired comparison on 10 CV shuffles. "
        "Δ = mean paired R² difference vs. baseline; p from two-tailed paired t-test.",
    )
    fig.subplots_adjust(top=0.83, bottom=0.28)
    fig.savefig(FIGS / "05_model_comparison.png")
    plt.close(fig)
    print("wrote figures/05_model_comparison.png")


# =============================================================================
# FIGURE 08 — Coefficient robustness across corrections
# =============================================================================
def figure_08() -> None:
    surv = pd.read_csv(SURV)
    labels_map = {
        "aaa_BB%_zseason":   "AAA BB%",
        "aaa_K%_zseason":    "AAA K%",
        "aaa_ISO_zseason":   "AAA ISO",
        "aaa_BABIP_zseason": "AAA BABIP",
        "age_at_debut":      "Age at debut",
    }
    surv["label"] = surv["predictor"].map(labels_map)
    surv = surv.dropna(subset=["label"])
    order = ["AAA ISO", "AAA K%", "AAA BB%", "Age at debut", "AAA BABIP"]
    surv = surv.set_index("label").loc[order].reset_index()

    fig, ax = plt.subplots(figsize=(11, 6.5))
    xs = np.arange(len(surv))
    w = 0.35
    ax.bar(xs - w/2, surv["OLS_coef"], w, label="Unweighted OLS",
           color="#6699CC", edgecolor="black", linewidth=0.8, alpha=0.9)
    ax.bar(xs + w/2, surv["IPW_coef"], w, label="IPW-corrected",
           color="#EE8866", edgecolor="black", linewidth=0.8, alpha=0.9)

    # value labels
    for i, (o, ip) in enumerate(zip(surv["OLS_coef"], surv["IPW_coef"])):
        ax.text(i - w/2, o + (0.15 if o > 0 else -0.15), f"{o:+.2f}",
                ha="center", va="bottom" if o > 0 else "top",
                fontsize=10, fontweight="bold")
        ax.text(i + w/2, ip + (0.15 if ip > 0 else -0.15), f"{ip:+.2f}",
                ha="center", va="bottom" if ip > 0 else "top",
                fontsize=10, fontweight="bold")

    ax.set_xticks(xs)
    ax.set_xticklabels(surv["label"])
    ax.axhline(0, color="black", lw=0.8)
    ax.set_ylabel("Standardized coefficient on MLB wRC+")
    ax.legend(loc="upper right", framealpha=0.9)
    add_title_and_subtitle(
        fig,
        "Skill-model coefficients: unweighted OLS vs. IPW-corrected",
        "Bars show standardized coefficients under the unweighted specification and "
        "after inverse probability weighting for cohort selection.",
    )
    fig.subplots_adjust(top=0.83)
    fig.savefig(FIGS / "08_coefficient_robustness.png")
    plt.close(fig)
    print("wrote figures/08_coefficient_robustness.png")


# =============================================================================
# FIGURE 09 — NEW: before/after specification correction
# =============================================================================
def figure_09() -> None:
    # Numbers documented in NOTES.md — uncorrected vs corrected pipelines
    labels = ["AAA ISO", "AAA K%", "AAA BB%", "AAA BABIP", "Age"]
    uncorrected = [+6.32, -2.96, +2.86, +0.55, -6.25]
    corrected   = [+5.48, -3.54, +2.64, +0.43, -1.92]

    fig, ax = plt.subplots(figsize=(11.5, 6.5))
    xs = np.arange(len(labels))
    w = 0.35
    b1 = ax.bar(xs - w/2, uncorrected, w, label="Uncorrected pipeline (N = 624)",
                color="#D3A5A5", edgecolor="black", linewidth=0.8, alpha=0.9)
    b2 = ax.bar(xs + w/2, corrected, w, label="Corrected pipeline (N = 486)",
                color="#5A7CA6", edgecolor="black", linewidth=0.8, alpha=0.9)

    for i, (u, c) in enumerate(zip(uncorrected, corrected)):
        ax.text(i - w/2, u + (0.25 if u > 0 else -0.25), f"{u:+.2f}",
                ha="center", va="bottom" if u > 0 else "top",
                fontsize=10.5, fontweight="bold", color="#7B3F3F")
        ax.text(i + w/2, c + (0.25 if c > 0 else -0.25), f"{c:+.2f}",
                ha="center", va="bottom" if c > 0 else "top",
                fontsize=10.5, fontweight="bold", color="#2C4A6E")

    # highlight the age collapse specifically
    ax.annotate(
        "Age coefficient collapsed\nfrom −6.25 to −1.92 (~70%)\nafter removing temporal leakage",
        xy=(4 + w/2, -1.92), xycoords="data",
        xytext=(3.3, -4.7), textcoords="data",
        fontsize=11.5, ha="center", color="#333",
        bbox=dict(boxstyle="round,pad=0.4", facecolor="#FFF3B0",
                  edgecolor="#B8860B", linewidth=1),
        arrowprops=dict(arrowstyle="->", color="#B8860B", lw=1.5,
                        connectionstyle="arc3,rad=-0.15"),
    )

    ax.set_xticks(xs)
    ax.set_xticklabels(labels)
    ax.axhline(0, color="black", lw=0.8)
    ax.set_ylabel("Standardized coefficient on MLB wRC+")
    ax.legend(loc="upper right", framealpha=0.9)
    ax.set_ylim(-7.5, 8.5)
    add_title_and_subtitle(
        fig,
        "Skill-model coefficients: uncorrected vs. corrected pipeline",
        "Uncorrected pipeline used career-PA-weighted AAA aggregates and \"age in final AAA season.\"  "
        "Corrected pipeline restricts to pre-debut AAA seasons and uses age at MLB debut.",
    )
    fig.subplots_adjust(top=0.83)
    fig.savefig(FIGS / "09_before_after_correction.png")
    plt.close(fig)
    print("wrote figures/09_before_after_correction.png")


def main() -> None:
    df = pd.read_csv(DATA)
    figure_02(df)
    figure_03()
    figure_05()
    figure_08()
    figure_09()
    print("\nDone. Regenerated 5 headline figures at figures/.")


if __name__ == "__main__":
    main()
